name: Hello World Workflow

on:
  push:
    branches:
      - main  # or any branch you want

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"

